CDCgov/cfa-immunization-uptake-projection

iup/build_projection_model.py
iup/get_uptake_data.py
iup/make_projections.py
scripts/projection_script.py

This is the Python version of my original R, consisting of three functions (in /iup) and a script that calls them sequentially (in /scripts). Either IIS or NIS data is imported and formatted, a linear regression model is fit to the per-day incident uptake, and projections from this linear model are generated. Projections are returned as a DataFrame in the same format as the original data.
This code is meant to be minimal. Many features (some of which were present in the R version) are omitted here, e.g.:
- scaling between data sets
- interpolation of dates
- ability to specify any model other than:   uptake ~ 1 + time_elapsed + previous_uptake + time_elapsed*previous_uptake
- group-level variation on state or calendar year
- quantification of projection uncertainty
- any graphical …

First Python version with simple architecture

---

iup/__init__.py
scripts/config_template.yaml
scripts/main.py

This uses the .over() approach to accommodate arbitrary grouping factors. The user now specifies in the config .yaml file which grouping factors to use from each data set, giving both the names of the relevant NIS columns as well as the desired names for these columns. The desired names for the grouping factor columns ought to match across any data sets that will be pooled together into the same model. A new function `extract_group_names` verifies this.
This PR does NOT include any testing - I will save that for later. 
So, please ignore PRs #49, #50, and #51. These should be kept a little while longer for reference, but not merged. This PR is the one that should be thoroughly reviewed and merged to permit arbitrary grouping factors.

Generalization for arbitrary grouping factors

---

iup/__init__.py
tests/test_uptake_data.py

This PR deletes the intermediate classes between ValidatedData and the end data types for observed data (Incident/CumulativeUptakeData) and forecasts (Quantile/SampleForecast). Each class has slightly different validation methods. In this way, the ValidatedData is a pool of functions, where different functions are used by multiple subclasses. The pro of this architecture is it is clear and easy to understand, while the con is that some functions are not meaningful for some classes but they can still be called. This is explicit for `split_train_test` function, which should not be available for any forecast types. Maybe consider to put it under both Incident&CumulativeUptakeData. However, other functions like 'date_to_*' can be useful for forecast types as well. 
Another note is that, the …

Refactor data type and forecast type

---

iup/__init__.py
tests/test_data_cleaning.py
tests/test_model_building.py
tests/test_uptake_data.py

- Rename the underlying data/forecast object as `Data`
- Simplify schema validations into a single method
- Add a validation that cumulative uptake estimates must be in [0, 1]
- Tweak tests to account for this new validation
- Methods on `Data` and its subclasses return normal `pl.DataFrame`s. Tweak one or two parts of the current uptake model to account for this.

Data refactor

---

iup/__init__.py
iup/models.py
scripts/main.py
tests/test_linear_incident_uptake_model.py

Note that the LinearIncidentUptakeModel must return cumulative projections. The reason is that if projections begin mid-season, cumulative projections will include the uptake that is already known, but incident projections won't. So cumulative projections are returned, and from there they can be converted to incident (as shown in the main.py script).
I also fixed a few issues in the current main branch that Pylance flagged on my local machine.
Resolves #31

Refactored Linear Incident Uptake Model to return projections separately, rather than as attributes

---

.pre-commit-config.yaml
iup/__init__.py
iup/eval.py
tests/test_evaluation.py
tests/test_linear_incident_uptake_model.py
tests/test_uptake_data.py

To harmonize with https://github.com/cdcent/cfa-repo-template/pull/38
The `ruff check` hook does what we used to use [isort](https://pycqa.github.io/isort/) to do
See https://github.com/cdcent/cfa-predict-handbook/pull/339/files for how to get VSCode to do this work automatically on save, so that pre-commit and VSCode are doing the same thing

Update ruff pre-commit hooks

---

iup/__init__.py
iup/eval.py
iup/models.py
iup/plot_projections.py
scripts/config_template.yaml
scripts/main.py
tests/test_data_cleaning.py
tests/test_evaluation.py
tests/test_linear_incident_uptake_model.py
tests/test_uptake_data.py

After merging #75, some incompatibilities surfaced:
- NIS API data have different column names than our data objects expect (e.g. "time_end" vs. "date"). Also, NIS API data have many columns that are not grouping factors (e.g. "vaccine", "indicator", "indicator_type"). To solve this, after calling on NIS API, `main.py` now drops and renames columns to achieve the minimalist schema expected by our data objects like CumulativeUptakeData. This extra behavior is controlled from the config file.
- NIS API data may encompass multiple seasons (whereas the vax uptake code had tacitly assumed exactly one season per data set). Relatedly, NIS API data does not include the rollout dates for each season. To solve this, `insert_rollout` can now recognize multiple rollout dates per data set. This …

Adjustments to insure compatibility with NIS API

---

iup/__init__.py
tests/test_linear_incident_uptake_model.py

- Pass the season start month and day as function arguments
- The unit test returns two separate values, so we make sure it isn't sending all values in the same direction

Refactor season splitter

---

scripts/model_demo.r

I have written an R script to explore a few model structures with full posterior predictions. This R script is not intended to be a user-friendly final product; it is merely personal scratchwork. Moreover, there are some scientific shortcomings - most notably some foolishly naive priors for both models described below. But its preliminary exploration shows a few results worth noting.
The data span the first historical date through 2024-11-30, for both covid and flu. Two model structures are explored:
- Linear Incident Model (LIM): incident uptake this week is linearly related to incident uptake last week and to time-since-rollout. This model predicts entire trajectories of uptake.
- Cumulative Hill Model (CHM): cumulative uptake follows the shape of a Hill function. This model predicts …

R script to explore models

---

Makefile
iup/eval.py
scripts/eval.py
scripts/forecast.py

This PR add the last functionality in the pipeline, evaluation. The metric will be calculated for different forecast end dates and for each model. This PR hasn't been tested with real data yet, i.e, the pipeline hasn't been run entirely.

Pipeline setup step 3: Add eval.py

---

Makefile
iup/__init__.py
scripts/config_template.yaml
scripts/eval.py
scripts/forecast.py
scripts/preprocess.py
tests/test_uptake_data.py

I ran the three scripts in the pipeline (preprocess.py, forecast.py, and eval.py) and found several things I wanted to improve:
- Several of the UptakeData methods are edited, along with their type-hinting, to return the correct UptakeData subclass, rather than generic polars data frames. This cleans up some of the excess type enforcing from the scripts.
- I clarified the way forecast dates are dealt with. Previously, every week between `["timeframe"]["start"]` and `["timeframe"]["end"]` in the config was used as a forecast date, resulting in multiple forecast trajectories of progressively shorter forecast horizons. Now, only the dates explicitly specified in `["timeframe"]["start"]` are used as forecast dates. If only one `["timeframe"]["start"]` is specified, then only one trajectory …

Several pipeline improvements

---

scripts/config_template.yaml

Shrinking the standard deviations in the prior distributions helps prevent some of the unstable trajectories. This is a short-term fix so that we can keep developing the codebase, without such nonsensical trajectories interfering with evaluating/plotting. I also fixed some mistakes with commas in the config template.

Adjusted priors for linear incident uptake model

---

docs/model_development.md

There are many directions we could take the refining of existing models and/or introduction of new model structures. I have made a document to summarize where we are now, some of the issues observed, and ideas for model development.

Document explaining model structures and development plans

---

scripts/model_demo.r

I have updated the R demo to incorporate hyperparameters into the Hill model that allow the final uptake and the half-maximal date to vary by season. Because this is just in the R demo, which is for brainstorming and will not be part of the final codebase, it doesn't require a detailed review. This is just to demonstrate few points, using the flu data.
As a reminder, here is what the entirety of the available flu data looks like:
If a Hill model is fit to these data, and then a forecast for the 2024/25 season is made from late October 2024 onward, we get:
Notice how 1) the forecast does not align with the data on the forecast date, and 2) the 95% credible interval starts off wide without widening much into the future.
Now we do the same thing, but including hyperparameters to allow the …

Hyperparameters for season in the Hill model (in R demo only)

---

iup/models.py

Super small PR here - just a few lines! Dates (the `time_end` column) is already sorted chronologically before any operations (e.g. intervals between dates, days since rollout, etc.) are applied to it. I've just added a few assert statements to check this.
This will close #43

Assert that dates are sorted chronologically

---

iup/__init__.py
iup/models.py
scripts/.gitignore
scripts/config_template.yaml
scripts/eval.py
scripts/forecast.py
scripts/postprocess.py
scripts/preprocess.py
tests/test_data_cleaning.py
tests/test_linear_incident_uptake_model.py

There are some bugs in pipeline, which I am searching out and solving. So far, I have found and fixed the following:
- Different filtering terms are required for the historical vs. recent forms of the NIS data within a vaccine type. E.g. for covid, the historical data requires `domain_type` of `overall` and `domain` of `overall`, whereas the recent data requires `domain_type` of `age` and `domain` of `18_ years`. You can now use multiple filtering terms to make sure neither the historical nor the recent data are accidentally filtered out during preprocessing.
- Many operations to prepare the data for model fitting (e.g. converting cumulative to incident) must be performed over some grouping factors. Season is now one of these grouping factors (e.g. so that the incident uptake on the first …

Clean up pipeline bugs

---

scripts/config_template.yaml
scripts/preprocess.py

In anticipation of refactored models that require the estimated error in observed uptake, this PR adds the standard deviation of observed uptake as a column in the preprocessed data.
I don't know how the upper and lower bounds of the "95% confidence intervals" in the NIS data are calculated. But with a truncated normal distribution in mind to describe the observation error, I have taken the width of the reported 95% confidence interval, divided by 2, and then divided by ~1.96 to estimate a standard deviation of sorts for the observed uptake.

Std dev of estimate as a data column

---

Makefile
iup/models.py
scripts/config_template.yaml
scripts/forecast.py
scripts/postprocess.py

- Add `plot_individual_projections`  in `postprocess.py` to allow plotting individual samples vs data. 
- Add `plot_summary` in `postprocess.py` to allow plotting mean, 95% credible interval with data. 
Currently, line plot is used instead of area because the challenge of using alt.area on pivotted quantile data. This is my trial code (no error but only returned blank):
```
interval = alt.Chart(plot_new_data).transform_filter(
datum.type == 'pred'
).transform_quantile(
"estimate",probs = [0.0025,0.5,0.975],as_=["quantile","estimate"],  # Calculate quantile for each grouping factor #
groupby=["time_end","season","forecast_start","model"]
).transform_pivot(
"quantile", groupby=["time_end"], value="estimate" # Convert long data frame to wide data frame #
).mark_area(opacity=0.3,color = …
```

Add individual projections and interval in plotting

---

iup/__init__.py
tests/test_linear_incident_uptake_model.py
tests/test_uptake_data.py

- Assert that incident uptakes are also proportions
- Rework tests to match, by dividing all the uptakes by 10
Resolves #68

Validate incident uptake

---

docs/model_details.md
iup/models.py
iup/utils.py
scripts/config_template.yaml
scripts/preprocess.py
tests/test_generic_model.py
tests/test_hill_model.py

The Hill model is refactored to handle arbitrary grouping factors (including but not limited to season), separate observation from latent true uptake, etc. See docs/model_details.md for the full description of this model.
This is currently a work in progress. In particular, I am running into `Segmentation fault (core dumped)` when I run the model on flu data across 14 seasons and 54 states/jurisdictions. I did not expect this to be a large-enough data set or a complex-enough model to crash my CPU, so more investigation must follow.

Refactor Hill Model

---

iup/models.py

This is a very minor change - I just learned how to add links to docstrings. Now the docstrings describing each model structure link to our model_details doc.
This will resolve #126

Added link to model_details.md in model docstrings

---

iup/utils.py

The standardization utility now handles NaNs consistently and does not apply the Bessel correction, regardless of whether the input is a numpy ndarray or a polars expression. I tried to streamline the function to look cleaner, but lurking around every corner was some operation or conditional that required separating the ndarray vs. expression cases anyway. I don't think this is worth any more effort.
This will address #128

More careful standardization

---

scripts/model_demo.r

This requires no code review - I've merely replaced the outdated stuff in my scratchwork script ("model_demo.r") with some rudimentary posterior predictive plots. There is plenty to improve, but I think this shows we are on the right track.
I load the flu data and the logistic+linear model posterior that this repo produces as a .parquet (see #143). For each season from 2009/2010 through 2021/2022, I plot the mean predicted latent true uptake vs. the data across states. (The 95% credible interval on the latent true uptake is also included, but it is usually quite thin.)
Note that the model was fit with 1 chain (not enough) using 500 warmups (not enough) and 500 samples (not enough), so there is room for immediate improvement.
Here's an example of the 2016-2017 season.
Since this requires …

Posterior predictive check plots

---

iup/__init__.py
iup/models.py
scripts/fit.py
scripts/forecast.py
tests/test_uptake_data.py

The `forecast.py` script is now much shorter and clearer, taking full advantage of the dictionary of fit models that @Fuhan-Yang created for us in #150. In the midst of this, #134 is addressed by trimming the test data down to dates and seasons _only_ before passing to `.predict()`.

Refactor of forecast.py script

---

iup/models.py
scripts/config_template.yaml
scripts/fit.py

If there are multiple MCMC chains for model fitting (and there should be), they now run in parallel. MCMC control parameters are now separated from model parameters in the config to set up the parallelization a little more easily.
This resolves issue #120. 
This also resolves issue #160, because that Arviz warning was basically saying that we should run more than 1 MCMC chain.
This also resolves issue #110, because I also split the random seed that initializes the model into two children: one for model fitting and one for prediction.

Parallelized numpyro chains

---

Makefile
iup/eval.py
scripts/config_template.yaml
scripts/eval.py
scripts/postprocess.py
tests/test_evaluation.py

- Updated iup.eval.py: 
1. Cleaned up previous metrics
2. Added a new function `abs_diff()` that returns a function to calculate absolute difference between predictions and observed data at specific date. 
3. Added a new function `summarize_score()` to loop through all score functions given observed data and predictions. Thanks for insights from @afmagee42 !
- Updated scripts/eval.py:
1. Converted prediction distribution into quantiles, allowing them to compare with observed data. 
2.  Get the functions that are returned by `abs_diff()`, and calculate together with `mspe()`. 
A long format of pl.DataFrame is returned, with `score_name` and `score_value`, grouped by `model`, `forecast_start` and `quantile`. Note that now model needs to be specified as `HillModel` to avoid the error (`lium` …

Update evaluation metrics for sample forecasts

---

iup/utils.py
scripts/diagnostics.py
scripts/fit.py
scripts/forecast.py
tests/test_utils.py

Per discussion in #166, it's more clear to represent the keys in model dictionary using tuple than string. Excise `parse_name_and_date()`.
Resolves #166

Excise parse_name_and_date

---

Makefile
scripts/figs_demo.py
scripts/forecast.py

While making plots for a demo presentation, I realized:
1) We generate forecasts to compare vs. the test data, but no posterior checks to compare vs. the training data.
2) The model's forecasts are substantially worse than the model's fit to training data.
3) The pipeline at times feels clunky, and it can be tricky to not overwrite results that took a long time to get.
This PR only deals with 1. I will make issues for 2 (#185) and 3 (#186).
Essentially, I added posterior checks as an output of the `forecast.py` script, and I adjusted the Makefile accordingly. 
The other altered file, `figs_demo.py`, is my notebook-in-progress to make custom figures for the demo presentation that sparked all this. No need to review this in great detail, since we may end up pruning it out of the repo later. …

Posterior Checks

---

Makefile
scripts/viz.py

- Debugged altair by having one single data source for multiple charts. 
Now if `make viz`, we should see trajectories of observed data along with other sample predictions; prediction interval (95% for now, can change in yaml) with mean trajectories and points from observed data; point plot of MSPE and absolute error of end-of-season uptake. 
- Integrated to the new Makefile structure. Connect streamlit as proposed in #195.
- Working on adding interaction: when mouse hovers on the plot, data will show up. 
Problems to solve: stop responding when plotting `geography` dimension, may be related to cache
Resolves #187 #190

Refactor streamlit

---

README.md

In my last update to the README, I forgot to clarify that there may be different commands to enter a uv virtual environment. This depends on your operating system, which terminal you are using, whether you use custom venv names, etc., so it can differ from user to user. The README now clarifies that `.venv/bin/activate`, `.venv/Scripts/activate`, etc. are just examples of what the enter-my-virtual-environment command might be.

Clarify uv virtual environment

---

scripts/gam_k.R

Before switching to Bayesian framework, I did a quick EDA based on today's discussion: how does gam perform given different number of basis functions on cumulative and incidental data?
Conditions: 
1. Flu vaccine uptake data from NIS is used.  
2. Model is assumed to be log-normal distributed (log link function)
3. Cubic basis spline function is used
4. Incidence data is calculated as the difference of cumulative data, and the first "0" point is trimmed to ensure all the data is eligible for log link function.
5. Training and test data is split on 2023-07-01. Season 2023/2024 is used for test. 
Methods:
1. GAM model is fitted given the number of basis functions (k) varied between 5 and 15. 
2. Fitted values and predictions are plotted for each k.
3. MSPE is calculated between test data …

EDA on number of basis functions given cumulative and incidental uptake data
